dependencies {
  api(project(":mall-cloud-common:mall-cloud-common-core"))
  api("org.springframework.boot:spring-boot-starter-data-jpa")
  implementation("org.springframework.boot:spring-boot-configuration-processor")
  implementation(libs.querydsl.core)
  implementation(libs.querydsl.sql)
  implementation(libs.querydsl.jpa)
  annotationProcessor(libs.querydsl.apt)
  implementation(libs.commons.lang3)
  implementation(libs.commons.collections4)
  annotationProcessor(libs.annotation.api)
  annotationProcessor(libs.validation.api)
  annotationProcessor(libs.jackson.annotations)
  annotationProcessor(libs.jackson.databind)
}
