dependencies {
  api(project(":mall-cloud-common:mall-cloud-common-core"))
  api("org.springframework.boot:spring-boot-starter-data-jpa")
  implementation("org.springframework.boot:spring-boot-configuration-processor")
//  implementation(libs.querydsl.core)
//  implementation(libs.querydsl.sql)
//  implementation(libs.querydsl.jpa)
//  annotationProcessor(libs.querydsl.apt)
  api("com.querydsl:querydsl-jpa:5.0.0:jakarta")
  annotationProcessor("com.querydsl:querydsl-apt:5.0.0:jakarta")
  implementation(libs.commons.lang3)
  implementation(libs.commons.collections4)
  implementation(libs.validation.api)
  annotationProcessor(libs.annotation.api)
  annotationProcessor(libs.persistence.api)
  annotationProcessor(libs.jackson.annotations)
  annotationProcessor(libs.jackson.databind)
}
