server:
  port: 8080

spring:
  application:
    name: mall-gateway

  #  mvc:
  #    pathmatch:
  #      matching-strategy: ant_path_matcher

  cloud:
    gateway:
      routes:
        - id: mall-auth
          uri: lb://mall-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: mall-admin
          uri: lb://mall-admin
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true

  security:
    oauth2:
#      client:
#        registration:
#          messaging-gateway-oidc:
#            provider: gateway-client-provider
#            client-id: test_client
#            client-secret: secret
#            redirect-uri:  "{baseUrl}/login/oauth2/code/{registrationId}"
#            authorization-grant-type: authorization_code
#            client-authentication-method: client_secret_basic
#            scope:
#              - openid
#              - profile
##            client-name: messaging-gateway-oidcs
#        provider:
#          gateway-client-provider:
#            issuer-uri: http://localhost:8101
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8101
          jwk-set-uri: http://127.0.0.1:8101/oauth2/jwks

secure:
  ignore:
    urls: #配置白名单路径
      - "/doc.html"
      - "/swagger-resources/**"
      - "/swagger/**"
      - "/*/v3/api-docs"
      - "/*/*.js"
      - "/*/*.css"
      - "/*/*.png"
      - "/*/*.ico"
      - "/webjars/**"
      - "/actuator/**"
