server:
  port: 8080



spring:
  application:
    name: mall-gateway

  #  main:
  #    allow-bean-definition-overriding: true

  #  mvc:
  #    pathmatch:
  #      matching-strategy: ant_path_matcher

  redis:
    host: localhost
    port: 6379
    database: 0
    password:

  cloud:
    gateway:
      routes:
        - id: mall-auth
          uri: lb://mall-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: mall-auth-login
          uri: lb://mall-auth
          predicates:
            - Path=/login
          filters:
            - PreserveHostHeader
        - id: mall-auth-token
          uri: lb://mall-auth
          predicates:
            - Path=/oauth2/token
          filters:
            - PreserveHostHeader
        - id: mall-auth-authorize
          uri: lb://mall-auth
          predicates:
            - Path=/oauth2/authorize
          filters:
            - PreserveHostHeader
        - id: mall-admin
          uri: lb://mall-admin
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1

      discovery:
        locator:
          enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          #          issuer-uri: http://127.0.0.1:8101
          jwk-set-uri: http://127.0.0.1:8101/oauth2/jwks
#      client:
#        registration:
#          messaging-gateway-oidc:
#            provider: gateway-client-provider
#            client-id: test_client
#            client-secret: secret
#            redirect-uri:  "{baseUrl}/login/oauth2/code/{registrationId}"
#            authorization-grant-type: authorization_code
#            client-authentication-method: client_secret_basic
#            scope:
#              - openid
#              - profile
##            client-name: messaging-gateway-oidcs
#        provider:
#          gateway-client-provider:
#            issuer-uri: http://localhost:8101

secure:
  ignore:
    urls:
      - "/actuator/**"
      - "/login"
      - "/oauth2/token"
      - "/oauth2/authorize"
      - "/doc.html"
      - "/swagger-resources/**"
      - "/swagger/**"
      - "/*/v3/api-docs"
      - "/*/*.js"
      - "/*/*.css"
      - "/*/*.png"
      - "/*/*.ico"
      - "/webjars/**"

