spring:
  cloud:
    nacos:
      discovery:
        enabled: true
        #        namespace: ${spring.profiles.active}
        server-addr: http://localhost:8848
        username: nacos
        password: nacos
      config:
        #        namespace: ${spring.profiles.active}
        server-addr: http://localhost:8848
        file-extension: yaml
logging:
  level:
    root: debug
