dependencies {
  api(project(":mall-cloud-common:mall-cloud-common-error"))
  implementation(libs.gson)
  implementation(libs.guava)
  implementation(libs.commons.lang3)
  implementation(libs.commons.codec)
  implementation(libs.commons.collections4)
  implementation(libs.transmittable.thread.local)
  implementation(libs.apm.toolkit.logback)
  implementation(libs.apm.toolkit.trace)
  implementation(libs.transmittable.thread.local)
  implementation(libs.slf4j.api)
  implementation(libs.cglib.nodep)
  implementation(libs.validation.api)
}
