server:
  port: 8201

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
  jpa:
    show-sql: true
    database: mysql
    #    database-platform: org.hibernate.dialect.MySQL5Dialec
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
  #      naming:
  #        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  redis:
    host: localhost
    port: 6379
    database: 0
    password:

swagger:
  enable: true
  groupName: mall-admin
  basePackage: com.github.lalifeier.mall.admin.presentation.rest
  version: 1.0.0
  title: 接口文档
  description: 接口文档
  contactName: lalifeier
  contactEmail: lalifeier@gmail.com
  contactUrl: https://lalifeier.github.io