version: "3.7"

networks:
  app_net:
    external: true

services:
  mall-gateway:
    image: mall/mall-gateway:1.0-SNAPSHOT
    container_name: mall-gateway
    ports:
      - 8080:8080
    networks:
      - app_net
    privileged: true
    restart: always
    environment:
      - TZ=Asia/Shanghai

  mall-auth:
    image: mall/mall-auth:1.0-SNAPSHOT
    container_name: mall-auth
    ports:
      - 8101:8101
    networks:
      - app_net
    privileged: true
    restart: always
    environment:
      - TZ=Asia/Shanghai

  mall-admin:
    image: mall/mall-admin:1.0-SNAPSHOT
    container_name: mall-admin
    ports:
      - 8201:8201
    networks:
      - app_net
    privileged: true
    restart: always
    environment:
      - TZ=Asia/Shanghai