dependencies {
  implementation(project(":mall-cloud-starter:mall-cloud-spring-cloud-starter"))
  implementation(project(":mall-cloud-starter:mall-cloud-mybatis-plus-spring-boot-starter"))
  implementation(project(":mall-cloud-starter:mall-cloud-xxl-job-spring-boot-starter"))
  implementation(project(":mall-cloud-business:mall-cloud-demo:mall-cloud-demo-api"))
//  implementation(project(":mall-cloud-business:mall-cloud-demo:mall-cloud-demo-grpc"))
//  implementation(project(":mall-cloud-business:mall-cloud-demo:mall-cloud-demo-dubbo"))
//  implementation(project(":mall-cloud-starter:mall-cloud-encrypt-body-spring-boot-starter"))
  implementation(project(":mall-cloud-starter:mall-cloud-redis-spring-boot-starter"))
//  implementation(project(":mall-cloud-starter:mall-cloud-rate-limiter-spring-boot-starter"))
//  implementation(project(":mall-cloud-starter:mall-cloud-signature-spring-boot-starter"))
  implementation(libs.grpc.spring.boot.starter)
  implementation(libs.druid.spring.boot.starter)
  implementation(libs.mybatis.plus.generator)
  implementation(libs.freemarker)
  implementation(libs.mysql.connector.java)
//  implementation(libs.dubbo.spring.boot.starter)
//  implementation("org.springframework.boot:spring-boot-starter-cache")
  implementation(libs.caffeine)
  implementation(libs.feign.okhttp)
  testImplementation("org.springframework.boot:spring-boot-starter-test")
  implementation(libs.mapstruct)
  annotationProcessor(libs.mapstruct.processor)
  implementation("org.springframework.boot:spring-boot-starter-validation")
  implementation("org.springframework.cloud:spring-cloud-starter-openfeign")
  implementation("org.springframework.cloud:spring-cloud-stream")
  implementation(libs.spring.boot.starter.actuator)
  implementation(libs.micrometer.registry.prometheus)
}
