dependencies {
  implementation(project(":mall-cloud-starter:mall-cloud-spring-cloud-starter"))
  implementation(project(":mall-cloud-starter:mall-cloud-mybatis-plus-spring-boot-starter"))
  implementation(project(":mall-cloud-starter:mall-cloud-xxl-job-spring-boot-starter"))
  implementation(project(":mall-cloud-business:mall-cloud-demo:mall-cloud-demo-api"))
  implementation(project(":mall-cloud-business:mall-cloud-demo:mall-cloud-demo-grpc"))
  implementation(project(":mall-cloud-business:mall-cloud-demo:mall-cloud-demo-dubbo"))
  implementation("net.devh:grpc-spring-boot-starter")
  // implementation("net.devh:grpc-server-spring-boot-starter")
  // compile("net.devh:grpc-client-spring-boot-starter")
  implementation("com.alibaba:druid-spring-boot-starter")
  implementation("com.baomidou:mybatis-plus-generator")
  implementation("org.freemarker:freemarker")
  implementation("mysql:mysql-connector-java")
  implementation("org.apache.dubbo:dubbo-spring-boot-starter")
  implementation("org.springframework.boot:spring-boot-starter-cache")
  implementation("com.github.ben-manes.caffeine:caffeine")
  implementation("io.github.openfeign:feign-okhttp")
  testImplementation("org.springframework.boot:spring-boot-starter-test")
  implementation("org.mapstruct:mapstruct")
  annotationProcessor("org.mapstruct:mapstruct-processor")
  implementation("org.springframework.boot:spring-boot-starter-validation")
  implementation("org.springframework.cloud:spring-cloud-starter-openfeign")
  implementation("org.springframework.cloud:spring-cloud-stream")
}
