server:
  port: 0

spring:
  profiles:
    active: dev

    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
      url: jdbc:jdbc:clickhouse://localhost:3306/default
      username: default
      password: 123456

  #  datasource:
  #    dynamic:
  #      primary: master
  #      strict: false
  #      datasource:
  #        master:
  #          type: com.alibaba.druid.pool.DruidDataSource
  #          driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
  #          url: dbc:jdbc:clickhouse://localhost:3306/default
  #          username: root
  #          password: 123456
  #        slave:
  #          type: com.alibaba.druid.pool.DruidDataSource
  #          driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
  #          url: dbc:jdbc:clickhouse://localhost:3307/default
  #          username: root
  #          password: 123456

  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
      database-platform=: mysql
      dialect: org.hibernate.dialect.MySQL57Dialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true

#  redis:
#    host: localhost
#    port: 6379
#    database: 0
#    password:

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
