server:
  port: 0

spring:
  profiles:
    active: dev

#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
#    url: jdbc:jdbc:clickhouse://localhost:3306/default
#    username: default
#    password: 123456

  shardingsphere:
    datasource:
      names: master_ds, slave_ds_0
      master_ds:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url:  jdbc:mysql://localhost:3306/test_db_sharding_master?allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true&characterEncoding=utf8
        username: root
        password: 123456
      slave_ds_0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name:  com.mysql.cj.jdbc.Driver
        url:  jdbc:mysql://localhost:3306/test_db_sharding_slave0?allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true&characterEncoding=utf8
        username: root
        password: 123456

    rules:
      readwrite-splitting:
        data-sources:
          master-slave:
            type: Static
            props:
              auto-aware-data-source-name: master_ds
              write-data-source-name: master_ds
              read-data-source-names: slave_ds_0
          load-balancers:
            roundRobin:
              type: ROUND_ROBIN

    props:
      sql:
        show: true

  #  datasource:
  #    dynamic:
  #      primary: master
  #      strict: false
  #      datasource:
  #        master:
  #          type: com.alibaba.druid.pool.DruidDataSource
  #          driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
  #          url: dbc:jdbc:clickhouse://localhost:3306/default
  #          username: root
  #          password: 123456
  #        slave:
  #          type: com.alibaba.druid.pool.DruidDataSource
  #          driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
  #          url: dbc:jdbc:clickhouse://localhost:3307/default
  #          username: root
  #          password: 123456

  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

#  redis:
#    host: localhost
#    port: 6379
#    database: 0
#    password:

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
