server:
  port: 9000

spring:
  application:
    admin:
      enabled: true
  #      discovery:
  #        ignored-services: ${spring.application.name}

  security:
    user:
      name: admin
      password: 123456

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
