server:
  port: 18000

spring:
  profiles:
    active: dev

  #  mvc:
  #    pathmatch:
  #      matching-strategy: ant_path_matcher

  cloud:
    gateway:
      routes:
        - id: demo-service
          uri: lb://demo-service
          predicates:
            - Path=/demo/**
          filters:
            - StripPrefix=1
        #            - name: EncryptRequestFilterFactory
        #              args:
        #                publicKey: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoMYmYgTgI6Fb2TusBx0fwwJtxWi+jWiaL4snQVC00ySvgTSTkohTstMO59f4cgN9baNLKrydtsWuB0YG/+s5uxZxAI11BEPeQKIt02uGHH0Af5GlDAT0HUMbFPLWl3HTCLuNR/pwYu7ZtPFwPIEoiFUWbcAYJQK2Nffxd4XPPJNtI6FnQv7jF8Nna9Xdls/R4fMLHpG38VS3SEM/BB9fPrchwbmUIKeWEG29g35dcnLdP9RcpCPTO3Xq5w+m/JmdIIaplMSy5Z7OSrvjcigrtzLZMf4BLnkalekjUM2aPoG3Oa8kQtS0uVZECk2OqfkKCqdyT4g9Cjnf3kNDYyXV3wIDAQAB"
        #                privateKey: "MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCgxiZiBOAjoVvZO6wHHR/DAm3FaL6NaJoviydBULTTJK+BNJOSiFOy0w7n1/hyA31to0sqvJ22xa4HRgb/6zm7FnEAjXUEQ95Aoi3Ta4YcfQB/kaUMBPQdQxsU8taXcdMIu41H+nBi7tm08XA8gSiIVRZtwBglArY19/F3hc88k20joWdC/uMXw2dr1d2Wz9Hh8wsekbfxVLdIQz8EH18+tyHBuZQgp5YQbb2Dfl1yct0/1FykI9M7dernD6b8mZ0ghqmUxLLlns5Ku+NyKCu3Mtkx/gEueRqV6SNQzZo+gbc5ryRC1LS5VkQKTY6p+QoKp3JPiD0KOd/eQ0NjJdXfAgMBAAECggEAIPMrV6hnJXZDBD0CDz0tTsK3K5/BeerHutm6lFzNin54x7K2UfBFsx8lbWeqX/eOI8O1Oo+IhTZzacM02Qtk/A5n33SeWF7udHGoka12QW1vBjYbzOBRBZREvyDb0RL/bMk/ddKCaQxJqxdWaNgRrgs+OwUFDcTGAj6MCvJuHBxJs6I6lrl9uaLPvitmuVMUT3She3PAnqphu+h+bcU+emVOaEKgIGzHdjPDmyuCUF/GbjcIc46YXUhDq4llK1lkTWdPvtlSJPyYjimzVQNJ6BB1/DfwTXFRMldn2Vv96aqPZZCK8zn7bXcaNLRxs+KccmJafkTBb32Xprli8PXD0QKBgQDPCUZp8hqzuW1Q2nDM0oBJRRyr2GD8JB/7TZXNH3LYR5VtiJ40EdqKAw6nCEc1wJHztRRsBTk7wKuVDq6ajGgnEpvaIZdU0ykBgsJTL0l8pbMYs3B48LCkJo/v1gLQS+ygJvD9bVBOC/aXmhq/GDe2ZOhzedqlc7MxrfQHgH/GUQKBgQDGy/4vCLX5zvMdE8Kcxl90lvy4rniMkFHg4fs7A/KTiFUVRg6vAvUJU7nVpq3IY6Cb0Rv3ZQ9SOomqsXLO6yLvTm6a6xvjztdk6Rh/WekjvrTSmP11sGL3m96xAGm7WEkKdA2XlgCLF3zl+TwTWUthEMeLycVFF9Edgp40XBVdLwKBgA8dvT9lBuASbNHXcR7zS5yN6D7/yG0AcjlV+9cDMc5qw5VAwVRJ7WvgN0SozRI2ojFqCjis1PXw5lY2wTbVg5E+wZRWmYb+9+J9WpTaQgJQ0te92jtqT2tcyWuYc5IjyP4Uecn3HkLkirec79D+AqtViMdNoVItNWsuKUAW+L1RAoGAWRYnhXpY2mbUac5mIw1+z2euPzDoks1F9AoxJKRDO7wXrN3lTKZ9mr1rhQQZ0rhazBjseHRQZmAXO2gj8/hJgoZaaJA9wlv6CJ2wvblUEhGvRMUMqIXwA9hU9msh9rO8n7OcN7cf7TUMYp7LPjyA3DHByrIT9j+TFa9oKDyv0j8CgYEApx7sbuZcBXtDp/GGS6ulapyOuzjwYnPIc2ThKAKrkCuuN/DNgI6CZlzlnCz8+A5E9UI5Bixn7WLVaNa/+r4Sfrc6LjzWIv2+EuG/XfLbnpIeimF5kri1A1crmsEQTrGjeYLUkTCV/cZZ0sMNrpGutehTG/kJalopckIATV12X+I=
        #            encryptData: eabycHWn8eFCXpMiChRWtQpyUd0zxFzzOuLM9eLBLcW+difwvxxnI1i0TgDBSKSEZe1G8/g3xhZsnkUWBC815tETUGtKY9O034/F7DjydUf/3aNI64nReuYJ5soTRJT5zRKAOkFTi5DYnAFfMIBvkT1IQPPvAOdpKShgCW4b+rLkU/pH7DYyDztfMh+Z6wiarxERmCC2fhQJxvebl5JLx9fb7MNYclKqpL/um5TuzFDVbzu2SyxwIsrhtLzOaTwSWp/VY+dJtQ6S/Vozi3rESaU1yC3Dn7INECrFSgi1yumYrayBQ8SpsNmweEs8DGH0FNkzTeznz+AYn5ArfOPI4w=="
        #                whiteList:
        #                blackList:
        #            - name: EncryptResponseFilterFactory
        #              args:
        #                publicKey: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoMYmYgTgI6Fb2TusBx0fwwJtxWi+jWiaL4snQVC00ySvgTSTkohTstMO59f4cgN9baNLKrydtsWuB0YG/+s5uxZxAI11BEPeQKIt02uGHH0Af5GlDAT0HUMbFPLWl3HTCLuNR/pwYu7ZtPFwPIEoiFUWbcAYJQK2Nffxd4XPPJNtI6FnQv7jF8Nna9Xdls/R4fMLHpG38VS3SEM/BB9fPrchwbmUIKeWEG29g35dcnLdP9RcpCPTO3Xq5w+m/JmdIIaplMSy5Z7OSrvjcigrtzLZMf4BLnkalekjUM2aPoG3Oa8kQtS0uVZECk2OqfkKCqdyT4g9Cjnf3kNDYyXV3wIDAQAB"
        #                privateKey: "MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCgxiZiBOAjoVvZO6wHHR/DAm3FaL6NaJoviydBULTTJK+BNJOSiFOy0w7n1/hyA31to0sqvJ22xa4HRgb/6zm7FnEAjXUEQ95Aoi3Ta4YcfQB/kaUMBPQdQxsU8taXcdMIu41H+nBi7tm08XA8gSiIVRZtwBglArY19/F3hc88k20joWdC/uMXw2dr1d2Wz9Hh8wsekbfxVLdIQz8EH18+tyHBuZQgp5YQbb2Dfl1yct0/1FykI9M7dernD6b8mZ0ghqmUxLLlns5Ku+NyKCu3Mtkx/gEueRqV6SNQzZo+gbc5ryRC1LS5VkQKTY6p+QoKp3JPiD0KOd/eQ0NjJdXfAgMBAAECggEAIPMrV6hnJXZDBD0CDz0tTsK3K5/BeerHutm6lFzNin54x7K2UfBFsx8lbWeqX/eOI8O1Oo+IhTZzacM02Qtk/A5n33SeWF7udHGoka12QW1vBjYbzOBRBZREvyDb0RL/bMk/ddKCaQxJqxdWaNgRrgs+OwUFDcTGAj6MCvJuHBxJs6I6lrl9uaLPvitmuVMUT3She3PAnqphu+h+bcU+emVOaEKgIGzHdjPDmyuCUF/GbjcIc46YXUhDq4llK1lkTWdPvtlSJPyYjimzVQNJ6BB1/DfwTXFRMldn2Vv96aqPZZCK8zn7bXcaNLRxs+KccmJafkTBb32Xprli8PXD0QKBgQDPCUZp8hqzuW1Q2nDM0oBJRRyr2GD8JB/7TZXNH3LYR5VtiJ40EdqKAw6nCEc1wJHztRRsBTk7wKuVDq6ajGgnEpvaIZdU0ykBgsJTL0l8pbMYs3B48LCkJo/v1gLQS+ygJvD9bVBOC/aXmhq/GDe2ZOhzedqlc7MxrfQHgH/GUQKBgQDGy/4vCLX5zvMdE8Kcxl90lvy4rniMkFHg4fs7A/KTiFUVRg6vAvUJU7nVpq3IY6Cb0Rv3ZQ9SOomqsXLO6yLvTm6a6xvjztdk6Rh/WekjvrTSmP11sGL3m96xAGm7WEkKdA2XlgCLF3zl+TwTWUthEMeLycVFF9Edgp40XBVdLwKBgA8dvT9lBuASbNHXcR7zS5yN6D7/yG0AcjlV+9cDMc5qw5VAwVRJ7WvgN0SozRI2ojFqCjis1PXw5lY2wTbVg5E+wZRWmYb+9+J9WpTaQgJQ0te92jtqT2tcyWuYc5IjyP4Uecn3HkLkirec79D+AqtViMdNoVItNWsuKUAW+L1RAoGAWRYnhXpY2mbUac5mIw1+z2euPzDoks1F9AoxJKRDO7wXrN3lTKZ9mr1rhQQZ0rhazBjseHRQZmAXO2gj8/hJgoZaaJA9wlv6CJ2wvblUEhGvRMUMqIXwA9hU9msh9rO8n7OcN7cf7TUMYp7LPjyA3DHByrIT9j+TFa9oKDyv0j8CgYEApx7sbuZcBXtDp/GGS6ulapyOuzjwYnPIc2ThKAKrkCuuN/DNgI6CZlzlnCz8+A5E9UI5Bixn7WLVaNa/+r4Sfrc6LjzWIv2+EuG/XfLbnpIeimF5kri1A1crmsEQTrGjeYLUkTCV/cZZ0sMNrpGutehTG/kJalopckIATV12X+I=
        #            encryptData: eabycHWn8eFCXpMiChRWtQpyUd0zxFzzOuLM9eLBLcW+difwvxxnI1i0TgDBSKSEZe1G8/g3xhZsnkUWBC815tETUGtKY9O034/F7DjydUf/3aNI64nReuYJ5soTRJT5zRKAOkFTi5DYnAFfMIBvkT1IQPPvAOdpKShgCW4b+rLkU/pH7DYyDztfMh+Z6wiarxERmCC2fhQJxvebl5JLx9fb7MNYclKqpL/um5TuzFDVbzu2SyxwIsrhtLzOaTwSWp/VY+dJtQ6S/Vozi3rESaU1yC3Dn7INECrFSgi1yumYrayBQ8SpsNmweEs8DGH0FNkzTeznz+AYn5ArfOPI4w=="
        #                whiteList:
        #                blackList:
        #            - name: SignatureFilter
        #              args:
        #                whiteList:

        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/account/**
          filters:
            - StripPrefix=1
            #        - id: login
            #          uri: lb://account-service
            #          predicates:
            #            - Path=/login
            #          filters:
            #            - PreserveHostHeader
            #        - id: register
            #          uri: lb://account-service
            #          predicates:
            #            - Path=/register
            #          filters:
            #            - PreserveHostHeader

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: auth-service-login
          uri: lb://auth-service
          predicates:
            - Path=/login
          filters:
            - PreserveHostHeader
        - id: auth-service-oauth2
          uri: lb://auth-service
          predicates:
            - Path=/oauth2/**
          filters:
            - PreserveHostHeader
        - id: auth-service-userinfo
          uri: lb://auth-service
          predicates:
            - Path=/userinfo
          filters:
            - PreserveHostHeader
            #        - id: mall-account
            #          uri: lb://mall-account
            #          predicates:
            #            - Path=/account/**
            #          filters:
            #            - StripPrefix=1
            #        - id: mall-admin
            #          uri: lb://mall-admin
            #          predicates:
            #            - Path=/admin/**
            #          filters:
            #            - StripPrefix=1

      discovery:
        locator:
          enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://127.0.0.1:18000/oauth2/jwks
          issuer-uri: http://127.0.0.1:18000
  #      client:
  #        registration:
  #          messaging-gateway-oidc:
  #            provider: gateway-client-provider
  #            client-id: test_client
  #            client-secret: secret
  #            redirect-uri:  "{baseUrl}/login/oauth2/code/{registrationId}"
  #            authorization-grant-type: authorization_code
  #            client-authentication-method: client_secret_basic
  #            scope:
  #              - openid
  #              - profile
  ##            client-name: messaging-gateway-oidcs
  #        provider:
  #          gateway-client-provider:
  #            issuer-uri: http://localhost:8101

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password:
    mongodb:
      host: localhost
      port: 27017
      database: access_log
      username: root
      password: 123456
      authentication-database: admin

gateway:
  white-urls:
    - "/actuator/**"
    - "/login"
    - "/oauth2/**"
    - "/doc.html"
    - "/v3/api-docs"
    - "/v3/api-docs/swagger-config"
    - "/v3/api-docs/**"
    - "/swagger-ui/index.html"
    - "/favicon.ico"
    - "/*/*.html"
    - "/*/*.css"
    - "/*/*.js"
    - "/*/*.js"
    - "/*/*.css"
    - "/*/*.png"
    - "/*/*.ico"
    - "/webjars/**"
    - "/demo/**"
    - "/account/**"
  sign:
    enabled: false
    timeout: 6000
    white-urls:
      - "/actuator/**"
      - "/login"
      - "/oauth2/**"
      - "/doc.html"
      - "/v3/api-docs"
      - "/v3/api-docs/swagger-config"
      - "/v3/api-docs/**"
      - "/swagger-ui/index.html"
      - "/favicon.ico"
      - "/*/*.html"
      - "/*/*.css"
      - "/*/*.js"
      - "/*/*.js"
      - "/*/*.css"
      - "/*/*.png"
      - "/*/*.ico"
      - "/webjars/**"
      - "/demo/**"
      - "/account/**"

knife4j:
  gateway:
    enabled: true
    tags-sorter: order
    operations-sorter: order
    strategy: discover
    discover:
      enabled: true
      version: openapi3
      excluded-services:
        - gateway-service
      service-config:
        demo-service:
          order: 1
          group-name: Demo服务


management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    root: info
